src/rater/models/gym.py
from rater import app
from bson.objectid import ObjectId
from rater.models import Climber

db = app.config['MONGO']

class Gym:
    def __init__(self, name, address, website, owner_id, admins=None, _id=None, image_uri=None):
        self.id = _id if _id is not None else ObjectId()
        self.name = name
        self.address = address
        self.website = website
        self.owner_id = owner_id
        self.admins = admins if admins is not None else []
        self.image_uri = image_uri
    

    @staticmethod
    def from_owner_username(name, address, website, owner_username, admins=None, _id=None, image_uri=None):
        owner = Climber.find_by_username(owner_username)
        if owner is None:
            raise ValueError(f'No user found with username {owner_username}')
        return Gym(name, address, website, owner.id, admins, _id, image_uri)


    def save(self):
        # Check for unique gym name
        existing_gym = db.gyms.find_one({'name': self.name})
        if existing_gym is not None:
            raise ValueError(f'A gym with the name {self.name} already exists.')

        return db.gyms.insert_one(self.to_document())

    
    def update(self):
        # ensure gym with id exists
        existing_gym = db.gyms.find_one({'_id': self.id})
        if existing_gym is None:
            raise ValueError(f'A gym with the id {self.id} does not exist.')
        
        return db.gyms.update_one({'_id': self.id}, {'$set': self.to_document()})


    def get_owner(self):
        return Climber.find_by_id(self.owner_id)


    def to_document(self):

        return {
            '_id': self.id,
            'name': self.name,
            'address': self.address,
            'website': self.website,
            'owner': self.owner_id,
            'admins': self.admins,
            'image_uri': self.image_uri,
        }


    @staticmethod
    def from_document(doc):
        admins = doc['admins'] if 'admins' in doc else []

        return Gym(
            doc['name'],
            doc['address'] if 'address' in doc else None,
            doc['website'] if 'website' in doc else None,
            doc['owner'],
            admins,
            doc['_id'],
            doc['image_uri'] if 'image_uri' in doc else None,
        )


    @staticmethod
    def find_by_id(_id):
        if type(_id) is str:
            _id = ObjectId(_id)
        gym_doc = db.gyms.find_one({'_id': _id})
        if gym_doc is None:
            return None
        return Gym.from_document(gym_doc)
    

    @staticmethod
    def find_by_name(name):
        gym_doc = db.gyms.find_one({'name': name})
        if gym_doc is None:
            return None
        return Gym.from_document(gym_doc)


    @staticmethod
    def find_all():
        return [Gym.from_document(doc) for doc in db.gyms.find()]

    @staticmethod
    def get_favorite_gyms(climber):
        return [Gym.from_document(gym) for gym in db.gyms.find({'_id': {'$in': climber.gyms}})]
    
    @staticmethod
    def get_favorite_gyms_size(climber):
        return len([Gym.from_document(gym) for gym in db.gyms.find({'_id': {'$in': climber.gyms}})])

src/rater/controllers/gym.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from rater.forms import GymForm
from rater.models import Gym, Route, Climber

gym_bp = Blueprint('gym', __name__)


@gym_bp.route('/gym/create', methods=['GET', 'POST'])
@login_required
def create():
    form = GymForm()

    if form.validate_on_submit():

        try:
            # Create new gym
            gym = Gym.from_owner_username(name=form.name.data, address=form.address.data, website=form.website.data, owner_username=form.owner_username.data)
            # Save gym to database
            gym.save()
        except ValueError as e:
            errors = [str(e)]
            return render_template('gym/create.html', form=form, current_user=current_user, errors=errors)

        # Redirect to gym page
        return redirect(url_for('gym.search', gym_id=str(gym.id)))

    # Render create gym page
    return render_template('gym/create.html', form=form, current_user=current_user)


@gym_bp.route('/gym/search', methods=['GET'])
@login_required
def search():
    # Parse query parameters
    name = request.args.get('name', None)
    gym_id = request.args.get('gym_id', None)

    # Find gyms by name or by ID
    if name:
        gyms = Gym.find_all()
        gyms = [
            gym
            for gym in gyms
            if name.lower() in gym.name.lower()
        ]
    elif gym_id:
        gym = Gym.find_by_id(gym_id)
        if gym is not None:
            return render_template('gym/search.html', gyms=[gym], current_user=current_user)
        else:
            flash('Gym not found!')
            return redirect(url_for('gym.create'))
    else:
        gyms = Gym.find_all()

    favorite_gyms = Gym.get_favorite_gyms(current_user)
    favorite_ids = set([gym.id for gym in favorite_gyms])

    gyms = [
        gym
        for gym in gyms
        if gym.id not in favorite_ids
    ]

    return render_template('gym/search.html', gyms=gyms, current_user=current_user, favorite_gyms=favorite_gyms)


@gym_bp.route('/gym/remove_favorite/<gym_id>', methods=['GET'])
@login_required
def remove_favorite(gym_id):
    # Retrieve the gym
    gym = Gym.find_by_id(gym_id)
    if not gym:
        return redirect(url_for('gym.search'))

    # Remove the gym from the current user's favorites
    current_user.remove_favorite_gym(gym)

    # Redirect back to the gym's page
    flash(f'Removed {gym.name} from your favorites.')
    return redirect(url_for('gym.search'))

# gym.add_favorite route
@gym_bp.route('/gym/add_favorite/<gym_id>', methods=['GET'])
@login_required
def add_favorite(gym_id):
    # Retrieve the gym
    gym = Gym.find_by_id(gym_id)
    if not gym:
        return redirect(url_for('gym.search'))

    # Add the gym to the current user's favorites
    current_user.add_favorite_gym(gym)

    # Redirect back to the gym's page
    flash(f'Added {gym.name} to your favorites.')
    return redirect(url_for('gym.search'))


# gym.edit route
@gym_bp.route('/gym/edit/<gym_id>', methods=['GET', 'POST'])
@login_required
def edit(gym_id):
    # Retrieve the gym
    gym = Gym.find_by_id(gym_id)
    owner = gym.get_owner()
    if not gym:
        return redirect(url_for('gym.search'))

    # Check if the current user is an admin of the gym
    if not owner.id == current_user.id:
        flash('You are not authorized to edit this gym.')
        return redirect(url_for('gym.show', gym_id=gym.id))

    # Create the form
    form = GymForm(obj=gym)
    form.owner_username.data = owner.username

    if form.validate_on_submit():
        owner_username = form.owner_username.data
        owner = Climber.find_by_username(owner_username)

        if owner is None:
            flash('Owner not found!')
            return render_template('gym/edit.html', form=form, gym=gym, current_user=current_user)

        # Update the gym
        gym.name = form.name.data
        gym.address = form.address.data
        gym.website = form.website.data
        gym.owner_id = owner.id
        gym.image_uri = form.image_uri.data

        # Update the gym to in the database
        gym.update()

        # Redirect to the gym's page
        flash('Gym updated successfully.')
        return redirect(url_for('gym.search'))

    # Render the edit page
    return render_template('gym/edit.html', form=form, gym=gym, current_user=current_user)


# gym.show route
@gym_bp.route('/gym-page/<gym_id>', methods=['GET'])
def show(gym_id):
    # Retrieve the gym
    gym = Gym.find_by_id(gym_id)
    if not gym:
        return redirect(url_for('gym.search'))

    # Retrieve the routes for the gym
    routes = Route.find_by_gym_id(gym_id)

    # Render the gym's page
    return render_template('gym/read.html', gym=gym, routes=routes, current_user=current_user)

src/rater/controllers/route.py
import io
import base64
import qrcode

from bson import ObjectId
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from rater.forms import RouteForm
from rater.models import Gym, Route, Attempt

route_bp = Blueprint('route', __name__)


@route_bp.route('/route/create', methods=['GET', 'POST'])
@login_required
def create():
    form = RouteForm()

    if form.validate_on_submit():

        try:
            # convert gym_id to ObjectId
            gym_id = ObjectId(form.gym_id.data)

            # Create new route
            route = Route(form.name.data, form.color.data, gym_id)
            # Save route to database
            route.save()
        except ValueError as e:
            errors = [str(e)]
            return render_template('route/create.html', form=form, current_user=current_user, errors=errors)

        # Redirect to route page
        return redirect(url_for('route.view', route_id=str(route.id)))

    # Render create gym page
    return render_template('route/create.html', form=form, current_user=current_user)


@route_bp.route('/route/<route_id>')
@login_required
def view(route_id):
    route = Route.find_by_id(route_id)
    if route is None:
        return redirect(url_for('main.index'))

    climber_attempts = Attempt.find_by_route(route)
    estimate = route.get_grade_estimate()

    # Generate the QR code
    qrcode_img = qrcode.make(url_for('route.view', route_id=route_id, _external=True))

    # Save it to a BytesIO object
    buf = io.BytesIO()
    qrcode_img.save(buf)

    # Encode the image in base64 and convert it to a format that can be used in HTML
    qr_code_b64 = base64.b64encode(buf.getvalue()).decode()

    gym = Gym.find_by_id(route.gym_id)

    return render_template('route/read.html', route=route, current_user=current_user, climber_attempts=climber_attempts, estimate=estimate, qr_code_b64=qr_code_b64, gym=gym)

src/templates/gym/_macros.html
{% macro gym_card(gym, current_user) %}
<div class="card">
    <div class="card-body">
    <h5 class="card-title">{{ gym.name }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ gym.address }}</h6>
    {% if current_user.is_authenticated %}
        {% if current_user.is_favorite_gym(gym) %}
        <a href="{{ url_for('gym.remove_favorite', gym_id=gym.id) }}" class="btn btn-warning">Remove from favorites</a>
        {% else %}
        <a href="{{ url_for('gym.add_favorite', gym_id=gym.id) }}" class="btn btn-outline-warning">Add to favorites</a>
        {% endif %}
        {% if current_user.id == gym.owner_id or current_user.id in gym.admins %}
        <a href="{{ url_for('gym.edit', gym_id=gym.id) }}" class="btn btn-outline-primary">Edit gym</a>
        {% endif %}
    {% endif %}
    <a href="{{ gym.website }}" class="card-link">Gym Website</a>
    <a href="{{ url_for('gym.show', gym_id=gym.id) }}" class="card-link">View gym details</a>
    </div>
</div>
{% endmacro %}


{% macro route_card(route, current_user) %}
<a href="{{ url_for('route.view', route_id=route.id) }}" style="text-decoration: none; color: inherit;">
    <div class="card mb-3" style="background-color: {{ route.color }};">
        <div class="card-body text-center">
            <h5 class="card-title" style="color: white; text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">{{ route.name }}</h5>
            <p class="card-text" style="color: white; text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">{{ route.grade }}</p>
        </div>
    </div>
</a>
{% endmacro %}

src/templates/gym/read.html
{% extends 'base.html' %} {% from 'gym/_macros.html' import route_card %} {%
block content %}

<div class="bg-gray-900 py-6 sm:py-8 lg:py-12">
	<div class="mx-auto max-w-screen-xl px-4 md:px-8">
		<div class="grid gap-8 md:grid-cols-2">
			<!-- images - start -->
			<div class="grid gap-4 lg:grid-cols-5">
				<div
					class="relative overflow-hidden rounded-lg bg-gray-100 lg:col-span-4"
				>
					<img
						src="{{gym.image_uri}}"
						loading="lazy"
						alt="Image"
						class="h-full w-full object-cover object-center"
					/>
				</div>
			</div>
			<!-- images - end -->

			<!-- content - start -->
			<div class="md:py-8">
				<!-- name - start -->
				<div class="mb-2 md:mb-3">
					<span class="mb-0.5 inline-block text-gray-200"
						>By {{gym.get_owner().username}}</span
					>
					<h2 class="text-2xl font-bold text-white lg:text-3xl">
						{{gym.name}}
					</h2>
				</div>
				<!-- name - end -->
				<!-- route - start -->
				<div class="mb-4 md:mb-6">
					<span
						class="mb-3 inline-block text-sm font-semibold text-gray-500 md:text-base"
						>Routes</span
					>

					<div class="flex flex-wrap gap-2">
						{% if routes %} {% for route in routes %}
						<a
							class="no-underline flex p-2 items-center justify-center rounded-md border text-center text-sm font-semibold text-white transition duration-100 hover:bg-gray-600 hover:text-gray-800 active:bg-gray-200"
							href="{{ url_for('route.view', route_id=route.id) }}"
						>
							{{route.name}}
							<button
								type="button"
								class="ml-2 h-8 w-8 rounded-full bg-gray-500 ring-2 ring-transparent ring-offset-1 transition duration-100 hover:ring-gray-200"
								style="background-color: {{route.color}};"
							></button>
						</a>
						{% endfor %} {% else %}
						<p
							class="flex items-center justify-center bg-white text-center text-sm font-semibold text-white transition duration-100 hover:bg-gray-100 active:bg-gray-200"
						>
							No Routes
						</p>
						{% endif %}
					</div>
				</div>
				<!-- route - end -->

				<!-- shipping notice - start -->
				<div class="mb-6 flex items-center gap-2 text-gray-500">
					<svg
						fill="white"
						class="h-6 w-6"
						version="1.1"
						id="Layer_1"
						xmlns="http://www.w3.org/2000/svg"
						xmlns:xlink="http://www.w3.org/1999/xlink"
						viewBox="0 0 512 512"
						xml:space="preserve"
					>
						<g id="SVGRepo_bgCarrier" stroke-width="0"></g>
						<g
							id="SVGRepo_tracerCarrier"
							stroke-linecap="round"
							stroke-linejoin="round"
						></g>
						<g id="SVGRepo_iconCarrier">
							<g>
								<g>
									<path
										d="M256.001,101.02c-39.388,0-71.432,32.045-71.432,71.432c0,39.388,32.045,71.432,71.432,71.432 c39.388,0,71.432-32.045,71.432-71.432C327.433,133.065,295.389,101.02,256.001,101.02z M256,213.445 c-22.603,0-40.993-18.389-40.993-40.993s18.389-40.993,40.993-40.993s40.993,18.39,40.993,40.993 C296.993,195.056,278.603,213.445,256,213.445z"
									></path>
								</g>
							</g>
							<g>
								<g>
									<path
										d="M403.703,302.096h-63.715c28.369-43.321,43.249-87.709,43.249-129.644c0-70.159-57.079-127.238-127.238-127.238 s-127.238,57.079-127.238,127.238c0,41.935,14.881,86.323,43.249,129.644h-63.715L0,466.786h512L403.703,302.096z M159.202,172.453c-0.001-53.377,43.423-96.8,96.798-96.8s96.799,43.424,96.799,96.799c0,53.343-28.498,101.699-52.407,132.872 c-0.767,0.999-1.533,1.977-2.3,2.955c-0.781,0.997-1.563,1.981-2.344,2.956c-0.249,0.31-0.498,0.623-0.747,0.931 c-0.777,0.963-1.552,1.914-2.327,2.854c-0.249,0.301-0.497,0.604-0.745,0.903c-0.774,0.935-1.546,1.857-2.315,2.767 c-0.242,0.287-0.485,0.573-0.727,0.858c-0.774,0.911-1.545,1.81-2.313,2.696c-0.229,0.265-0.458,0.528-0.686,0.79 c-0.775,0.889-1.545,1.766-2.311,2.63c-0.216,0.244-0.431,0.485-0.646,0.727c-0.777,0.871-1.549,1.731-2.315,2.574 c-0.19,0.209-0.378,0.415-0.567,0.622c-0.783,0.859-1.563,1.708-2.333,2.537c-0.162,0.174-0.324,0.347-0.485,0.521 c-0.791,0.85-1.578,1.687-2.353,2.505c-0.123,0.129-0.244,0.256-0.365,0.383c-0.808,0.849-1.607,1.684-2.394,2.497 c-0.074,0.077-0.147,0.151-0.222,0.228c-0.827,0.853-1.645,1.69-2.445,2.502c-0.018,0.018-0.036,0.036-0.053,0.054 c-5.135,5.2-9.71,9.54-13.394,12.908C229.93,329.862,159.202,257.301,159.202,172.453z M124.712,332.535h69.609 c22.376,27.534,43.37,45.907,50.029,51.489c0.002,0.002,0.004,0.003,0.006,0.005c0.241,0.202,0.465,0.389,0.668,0.557 c0.014,0.011,0.025,0.021,0.04,0.032c0.396,0.328,0.721,0.596,0.96,0.789c0.019,0.016,0.03,0.025,0.05,0.041 c0.191,0.155,0.329,0.266,0.4,0.323c0.007,0.006,0.024,0.019,0.03,0.024l0.002,0.001h0.001l0.01,0.008l9.486,7.575l9.486-7.575 l0.01-0.008h0.001l0.002-0.001c0.006-0.005,0.022-0.018,0.03-0.024c0.071-0.057,0.209-0.167,0.4-0.323 c0.018-0.015,0.029-0.024,0.05-0.041c0.238-0.194,0.564-0.462,0.96-0.789c0.014-0.011,0.025-0.021,0.04-0.032 c0.203-0.168,0.426-0.355,0.668-0.557c0.002-0.001,0.004-0.003,0.006-0.005c6.66-5.583,27.653-23.955,50.029-51.489h69.609 l68.264,103.811H56.448L124.712,332.535z"
									></path>
								</g>
							</g>
						</g>
					</svg>
					<span class="text-sm text-white">{{gym.address}}</span>
				</div>
				<!-- shipping notice - end -->

				<!-- buttons - start -->
				<div class="flex gap-3">
					{% if current_user.is_authenticated and (current_user.id ==
					gym.owner_id or current_user.id in gym.admins) %}
					<a
						href="{{ url_for('gym.edit', gym_id=gym.id) }}"
						class="inline-block flex-1 rounded-lg bg-indigo-500 px-8 py-3 text-center text-sm font-semibold text-white outline-none ring-indigo-300 transition duration-100 hover:bg-indigo-600 focus-visible:ring active:bg-indigo-700 sm:flex-none md:text-base"
						>Edit</a
					>
					{%endif%} {% if current_user.is_authenticated and (current_user.id ==
					gym.owner_id or current_user.id in gym.admins) %}

					<a
						href="{{ url_for('route.create', gym_id=gym.id) }}"
						class="inline-block rounded-lg bg-gray-200 px-8 py-3 text-center text-sm font-semibold text-gray-500 outline-none ring-indigo-300 transition duration-100 hover:bg-gray-300 focus-visible:ring active:text-gray-700 md:text-base"
						>Add Route</a
					>
					{%endif%}
				</div>
				<!-- buttons - end -->
			</div>
			<!-- content - end -->
		</div>
	</div>
</div>
<!-- ====== Footer Section Start -->
<footer class="px-4 py-8 dark:bg-gray-800 dark:text-gray-400">
	<div
		class="container flex flex-wrap items-center justify-center mx-auto space-y-4 sm:justify-between sm:space-y-0"
	>
		<div class="flex flex-row pr-3 space-x-4 sm:space-x-8">
			<a href="/" class="text-indigo-600 text-lg">
				<strong>RouteRater</strong>
			</a>
			<ul class="flex flex-wrap items-center space-x-4 sm:space-x-8">
				<li>
					<a rel="noopener noreferrer" href="#">Terms of Use</a>
				</li>
				<li>
					<a rel="noopener noreferrer" href="#">Privacy</a>
				</li>
			</ul>
		</div>
		<ul class="flex flex-wrap pl-3 space-x-4 sm:space-x-8">
			<li>
				<a rel="noopener noreferrer" href="#">GitHub</a>
			</li>
			<li>
				<a rel="noopener noreferrer" href="#">Instagram</a>
			</li>
			<li>
				<a rel="noopener noreferrer" href="#">Twitter</a>
			</li>
		</ul>
	</div>
</footer>
<!-- ====== Footer Section End -->
{% endblock %}

src/templates/gym/search.html
{% extends 'base.html' %} {% from 'gym/_macros.html' import gym_card %} {% block
content %}

<!-- ====== Cards Section Start -->
<section
	class="bg-[#F3F4F6] pt-20 pb-10 lg:pt-[120px] lg:pb-20 flex items-center bg-gray-900"
>
	<div class="container mx-auto">
		<form
			class="flex flex-col space-y-3 sm:space-y-0 sm:flex-row sm:-mx-2 items-center justify-center"
			method="GET"
			action="{{ url_for('gym.search') }}"
		>
			<input
				type="search"
				placeholder="Search by gym name"
				aria-label="Search"
				name="name"
				value="{{ request.args.get('name', '') }}"
				class="px-6 py-3 bg-white border border-gray-200 rounded-lg sm:mx-2 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-300 focus:outline-none focus:ring focus:ring-opacity-40"
			/>

			<button
				class="px-6 py-3 text-md tracking-wide text-white capitalize transition-colors duration-300 transform bg-indigo-600 rounded-lg focus:ring focus:ring-blue-300 focus:ring-opacity-80 fo sm:mx-2 hover:bg-indigo-500 focus:outline-none focus:bg-indigo-500"
				type="submit"
			>
				Search
			</button>
		</form>
		{% if favorite_gyms %}
		<p class="text-3xl font-bold text-white">Your Favorite Gyms</p>
		<p class="mb-12 text-xl font-normal text-gray-200">
			All your favorite gyms in one place.
		</p>

		<div class="-mx-4 flex flex-wrap">
			{% for gym in favorite_gyms %}
			<div class="w-full px-4 md:w-1/2 xl:w-1/3">
				<div class="mb-10 overflow-hidden rounded-lg bg-white">
					<img src="{{gym.image_uri}}" alt="image" class="w-full h-64 object-cover" />
					<div class="p-8 text-center sm:p-9 md:p-7 xl:p-9">
						<h3>
							<a
								href="{{url_for('gym.show', gym_id=gym.id)}}"
								class="p-4 text-dark hover:text-primary mb-1 block text-xl font-semibold sm:text-[22px] md:text-xl lg:text-[22px] xl:text-xl 2xl:text-[22px]"
							>
								{{gym.name}}
							</a>
						</h3>
						<p class="text-body-color mb-7 text-base leading-relaxed">
							{{gym.address}}
						</p>
						{% if current_user.is_authenticated %} {% if
						current_user.is_favorite_gym(gym) %}
						<a
							href="{{ url_for('gym.remove_favorite', gym_id=gym.id) }}"
							class="p-4 text-body-color bg-indigo-600 hover:bg-white inline-block rounded-full border border-[#E5E7EB] py-2 px-7 text-base font-medium transition text-white hover:text-black"
						>
							Favorited ❤️
						</a>
						{% else %}
						<a
							href="{{ url_for('gym.add_favorite', gym_id=gym.id) }}"
							class="p-4 text-body-color hover:border-primary hover:bg-indigo-600 inline-block rounded-full border border-[#E5E7EB] py-2 px-7 text-base font-medium transition hover:text-white"
							>Add to favorites</a
						>
						{% endif %}
						<a
							target="_blank"
							href="{{ gym.website }}"
							class="p-4 text-body-color hover:border-primary hover:bg-indigo-600 inline-block rounded-full border border-[#E5E7EB] py-2 px-7 text-base font-medium transition hover:text-white"
							>Website 🔗</a
						>
						{% if current_user.id == gym.owner_id or current_user.id in
						gym.admins %}
						<a
							href="{{ url_for('gym.edit', gym_id=gym.id) }}"
							class="p-4 mt-2 text-body-color hover:border-primary hover:bg-indigo-600 inline-block rounded-full border border-[#E5E7EB] py-2 px-7 text-base font-medium transition hover:text-white"
							>Edit gym</a
						>
						{% endif %} {% endif %}
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% endif %} {% if gyms %}
		<p class="text-3xl font-bold text-white">Gyms</p>
		<p class="mb-12 text-xl font-normal text-gray-200">Find your next gym.</p>
		<div class="-mx-4 flex flex-wrap">
			{% for gym in gyms %}
			<div class="w-full px-4 md:w-1/2 xl:w-1/3">
				<div class="mb-10 overflow-hidden rounded-lg bg-white">
					<img src="{{gym.image_uri}}" alt="image" class="w-full h-64 object-cover" />
					<div class="p-8 text-center sm:p-9 md:p-7 xl:p-9">
						<h3>
							<a
								href="{{url_for('gym.show', gym_id=gym.id)}}"
								class="p-4 text-dark hover:text-primary mb-1 block text-xl font-semibold sm:text-[22px] md:text-xl lg:text-[22px] xl:text-xl 2xl:text-[22px]"
							>
								{{gym.name}}
							</a>
						</h3>
						<p class="text-body-color mb-7 text-base leading-relaxed">
							{{gym.address}}
						</p>
						{% if current_user.is_authenticated %} {% if
						current_user.is_favorite_gym(gym) %}
						<a
							href="{{ url_for('gym.remove_favorite', gym_id=gym.id) }}"
							class="p-4 text-body-color bg-indigo-600 hover:bg-white inline-block rounded-full border border-[#E5E7EB] py-2 px-7 text-base font-medium transition text-white hover:text-black"
						>
							Favorited ❤️
						</a>
						{% else %}
						<a
							href="{{ url_for('gym.add_favorite', gym_id=gym.id) }}"
							class="p-4 text-body-color hover:border-primary hover:bg-indigo-600 inline-block rounded-full border border-[#E5E7EB] py-2 px-7 text-base font-medium transition hover:text-white"
							>Add to favorites</a
						>
						{% endif %}
						<a
							target="_blank"
							href="{{ gym.website }}"
							class="p-4 text-body-color hover:border-primary hover:bg-indigo-600 inline-block rounded-full border border-[#E5E7EB] py-2 px-7 text-base font-medium transition hover:text-white"
							>Website 🔗</a
						>
						{% if current_user.id == gym.owner_id or current_user.id in
						gym.admins %}
						<a
							href="{{ url_for('gym.edit', gym_id=gym.id) }}"
							class="p-4 mt-2 text-body-color hover:border-primary hover:bg-indigo-600 inline-block rounded-full border border-[#E5E7EB] py-2 px-7 text-base font-medium transition hover:text-white"
							>Edit gym</a
						>
						{% endif %} {% endif %}
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% else %}
		<p class="text-3xl mb-12 font-bold text-center text-white">No Gyms Found</p>
		{% endif %}
	</div>
</section>
<!-- ====== Cards Section End -->
<!-- ====== Footer Section Start -->
<footer class="px-4 py-8 dark:bg-gray-800 dark:text-gray-400">
	<div
		class="container flex flex-wrap items-center justify-center mx-auto space-y-4 sm:justify-between sm:space-y-0"
	>
		<div class="flex flex-row pr-3 space-x-4 sm:space-x-8">
			<a href="/" class="text-indigo-600 text-lg">
				<strong>RouteRater</strong>
			</a>
			<ul class="flex flex-wrap items-center space-x-4 sm:space-x-8">
				<li>
					<a rel="noopener noreferrer" href="#">Terms of Use</a>
				</li>
				<li>
					<a rel="noopener noreferrer" href="#">Privacy</a>
				</li>
			</ul>
		</div>
		<ul class="flex flex-wrap pl-3 space-x-4 sm:space-x-8">
			<li>
				<a rel="noopener noreferrer" href="#">GitHub</a>
			</li>
			<li>
				<a rel="noopener noreferrer" href="#">Instagram</a>
			</li>
			<li>
				<a rel="noopener noreferrer" href="#">Twitter</a>
			</li>
		</ul>
	</div>
</footer>
<!-- ====== Footer Section End -->
{% endblock %}