src/rater/models/climber.py
from werkzeug.security import check_password_hash, generate_password_hash
from rater import app
from flask_login import UserMixin
from bson.objectid import ObjectId
import re

db = app.config['MONGO']

class Climber(UserMixin):
    def __init__(self, email, username, _id=None, password_hash=None, gyms=None, friends=None):
        self.id = _id if _id is not None else ObjectId()
        self.email = email
        self.username = username
        self.password_hash = password_hash
        self.gyms = gyms if gyms is not None else []
        self.friends = friends if friends is not None else []
        self.gym_id = None


    def set_password(self, password):
        self.password_hash = generate_password_hash(password)


    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


    def select_gym(self, gym_id):
        self.gym_id = gym_id


    def save(self):
        # Check for unique email and username
        if db.climbers.find_one({'email': self.email}) is not None:
            raise ValueError('An account with this email address already exists.')
        if db.climbers.find_one({'username': self.username}) is not None:
            raise ValueError('This username is already taken.')

        # Insert document into database
        return db.climbers.insert_one({
            '_id': self.id,
            'email': self.email,
            'username': self.username,
            'password_hash': self.password_hash,
        })


    def to_document(self):
        return {
            '_id': self.id,
            'email': self.email,
            'username': self.username,
            'password_hash': self.password_hash,
            'gyms': self.gyms,
            'friends': self.friends,
        }

    
    

    def is_favorite_gym(self, gym):
        return gym.id in self.gyms


    def add_favorite_gym(self, gym):
        if not self.is_favorite_gym(gym):
            self.gyms.append(gym.id)
            db.climbers.update_one({'_id': self.id}, {'$push': {'gyms': gym.id}})


    def remove_favorite_gym(self, gym):
        if self.is_favorite_gym(gym):
            self.gyms.remove(gym.id)
            db.climbers.update_one({'_id': self.id}, {'$pull': {'gyms': gym.id}})

    def get_friends(self):
        return [f for f in db.climbers.find({'_id': {'$in': self.friends}})]

    def get_friends_size(self):
        return len([f for f in db.climbers.find({'_id': {'$in': self.friends}})])

    def is_friend(self, user):
        return user.id in self.friends

    def add_friend(self, friend):
        if not self.is_friend(friend):
            self.friends.append(friend.id)
            db.climbers.update_one({'_id': self.id}, {'$push': {'friends': friend.id}})

    def remove_friend(self, friend):
        if self.is_friend(friend):
            self.friends.remove(friend.id)
            db.climbers.update_one({'_id': self.id}, {'$pull': {'friends': friend.id}})

    @staticmethod
    def from_document(doc):
        gyms = doc['gyms'] if 'gyms' in doc else []
        friends = doc['friends'] if 'friends' in doc else []
        return Climber(
            doc['email'],
            doc['username'],
            doc['_id'],
            doc['password_hash'],
            gyms,
            friends,
        )


    @staticmethod
    def find_by_email(email):
        climber_doc = db.climbers.find_one({'email': email})
        if climber_doc is None:
            return None
        return Climber.from_document(climber_doc)


    @staticmethod
    def find_by_username(username):
        climber_doc = db.climbers.find_one({'username': username})
        if climber_doc is None:
            return None
        return Climber.from_document(climber_doc)
    
    @staticmethod
    def find_many_by_username(username):
        regex = f".*{re.escape(username)}.*"  # Escape special characters in username
        climbers = db.climbers.find({'username': {'$regex': regex, '$options': 'i'}})
        return [Climber.from_document(climber) for climber in climbers]

    @staticmethod
    def find_by_id(_id):
        if type(_id) is str:
            _id = ObjectId(_id)
        climber_doc = db.climbers.find_one({'_id': _id})
        if climber_doc is None:
            return None
        return Climber.from_document(climber_doc)


    def get_id(self):
        return str(self.id)


    @property
    def is_authenticated(self):
        return True


    @property
    def is_active(self):
        return True


    @property
    def is_anonymous(self):
        return False

src/rater/controllers/climber.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, current_user, logout_user, login_required
from rater.forms import RegistrationForm, LoginForm, AttemptForm
from rater.models import Climber, Route, Attempt, Gym


climber_bp = Blueprint('climber', __name__)


@climber_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        # Create new climber
        climber = Climber(email=form.email.data, username=form.username.data)
        climber.set_password(form.password.data)

        # Save climber to database
        try:
            climber.save()
        except ValueError as e:
            errors = [str(e)]
            return render_template('climber/register.html', form=form, current_user=current_user, errors=errors)

        # Log in new user and redirect to index page
        login_user(climber)
        return redirect(url_for('index'))

    # Render sign-up page
    return render_template('climber/register.html', form=form, current_user=current_user)


@climber_bp.route('/login', methods=['GET', 'POST'])
def login():

    # if climber is logged in redirect to index page
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = LoginForm()

    if form.validate_on_submit():
        # Get climber from database
        climber = Climber.find_by_email(form.email.data)

        # Check if climber exists and password is correct
        if climber is None or not climber.check_password(form.password.data):
            errors = ['Invalid email or password']
            return render_template('climber/login.html', form=form, current_user=current_user, errors=errors)

        # Log in user and redirect to index page
        login_user(climber)
        return redirect(url_for('gym.search'))

    # Render login page
    return render_template('climber/login.html', form=form, current_user=current_user)


@climber_bp.route('/logout')
def logout():
    # Log out the current user
    logout_user()

    # Redirect to the login page
    return redirect(url_for('climber.login'))


@climber_bp.route('/profile')
def profile():
    attempts = Attempt.find_by_climber(current_user)
    current_user.get_favorite_gyms = lambda: Gym.get_favorite_gyms(
        current_user)
    current_user.get_favorite_gyms_size = lambda: Gym.get_favorite_gyms_size(
        current_user)
    current_user_attempts = len(attempts)
    return render_template('climber/profile.html', current_user=current_user, attempts=attempts, current_user_attempts=current_user_attempts)


@climber_bp.route('/profile/edit')
@login_required
def edit_profile():
    return render_template('climber/edit_profile.html')


@climber_bp.route('/profile/friends')
def friends():
    name = request.args.get('name', None)

    climbers = []
    if name:
        climbers = Climber.find_many_by_username(name)

    return render_template('climber/friends.html', current_user=current_user, climbers=climbers)


@climber_bp.route('/profile/add_friend/<user_id>', methods=['GET'])
@login_required
def add_friend(user_id):
    # Retrieve the gym
    user = Climber.find_by_id(user_id)
    if not user or current_user.is_friend(user):
        return redirect(url_for('climber.friends'))

    current_user.add_friend(user)

    # Redirect back to the gym's page
    flash(f'Added {user.username} to your favorites.')
    return redirect(url_for('climber.friends', current_user=current_user, climbers=[]))


@climber_bp.route('/profile/remove_friend/<user_id>', methods=['GET'])
@login_required
def remove_friend(user_id):
    user = Climber.find_by_id(user_id)
    if not user or not current_user.is_friend(user):
        return redirect(url_for('climber.friends'))

    current_user.remove_friend(user)

    flash(f'Removed {user.username} to your favorites.')
    return redirect(url_for('climber.friends', current_user=current_user, climbers=[]))


@climber_bp.route('/route/add/<route_id>', methods=["GET", "POST"])
@login_required
def add_attempt(route_id):
    form = AttemptForm()
    route = Route.find_by_id(route_id)

    if form.validate_on_submit():
        try:
            attempt = Attempt(route_id=route.id, climber_id=current_user.id,
                              success=form.success.data, grade=form.grade.data)
            attempt.save()
        except ValueError as e:
            errors = [str(e)]
            return render_template('route.view', route_id=route_id, errors=errors)

        flash(f'Added attempt for {route.name}.')
        return redirect(url_for('route.view', route_id=route_id))

    return render_template('route/add_attempt.html', route=route, form=form)

src/templates/climber/_macros.html
{% macro profile_card(current_user) %}

<div class="card profile_card text-center">
    <img src="/static/defaultuser.png" class="card-img-top rounded-circle w-50 mx-auto mt-3">
    <div class="card-body">
        <h4 class="card-title">{{ current_user.username }}'s Profile</h4>
        <a href="{{ url_for('climber.edit_profile') }}" class="btn btn-warning mt-2">Edit Profile</a>
    </div>
</div>

{% endmacro %}

{% macro gym_card(gym) %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ gym.name }}</h5>
        <p class="card-subtitle text-muted">{{ gym.address }}</p>
    </div>
</div>

{% endmacro %}

{% macro user_card(current_user, user) %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ user.username }}</h5>
        {% if current_user.is_friend(user) %}
            <a href="{{ url_for('climber.remove_friend', user_id=user.id) }}" class="btn btn-danger mt-2">Remove Friend</a>
        {% else %}
            <a href="{{ url_for('climber.add_friend', user_id=user.id) }}" class="btn btn-success mt-2">Add Friend</a>
        {% endif%}
    </div>
</div>

{% endmacro %}

{% macro friend_card(friend) %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ friend.username }}</h5>
    </div>
</div>

{% endmacro %}

{% macro attempt_card(att) %}

<div class="card mb-2">
    <div class="card-header">
        <h5 class="card-title mb-0">{{ att.route.name }}</h5>
    </div>
    <div class="card-body">
        <span class="badge {{ 'badge-success' if att.success else 'badge-danger' }}">
            {{ 'Success' if att.success else 'Failed' }}
        </span>
        <p class="card-text mt-2 mb-0">Date: {{ att.time }}</p>
        <p class="card-text mb-0">Grade: {{ att.grade }}</p>
    </div>
</div>

{% endmacro %}

src/templates/climber/edit_profile.html
{% extends 'base.html' %}

{% import 'climber/_macros.html' as macros %}

{% block content %}

<div class="container">
    <div class="edit_profile">
        <img src="/static/defaultuser.png" alt="">

        <form method="post">
        </form>

    </div>
</div>

{% endblock %}

src/templates/climber/friends.html
{% extends 'base.html' %}

{% from 'climber/_macros.html' import user_card %}

{% block content %}

<div class="container">

   <h1>Find New Friends</h1>

    <form class="form-inline mb-4" method="GET" action="/profile/friends">
        <input class="form-control mr-sm-2" type="search" placeholder="Search for a user" aria-label="Search" name="name" value="{{ request.args.get('name', '') }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

    {% for climber in climbers %}
        {{ user_card(current_user, climber) }}
    {% endfor %}

</div>

{% endblock %}

src/templates/climber/login.html
{% from "_formhelpers.html" import render_field, render_errors %}

{% extends "base.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center mb-4">Log in</h1>
      <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ render_field(form.password) }}
        {{ render_errors(errors) }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>
      </form>
      <p class="text-center">
        Need an account? <a href="{{ url_for('climber.register') }}">Register</a>.
      </p>
    </div>
  </div>
{% endblock %}

src/templates/climber/profile.html
{% extends 'base.html' %} {% import 'climber/_macros.html' as macros %} {% block
content %}
<div class="bg-gray-900 py-6 sm:py-8 lg:py-12">
	<div class="container mt-5 flex items-center justify-center">
		<div class="p-10 bg-white shadow-lg rounded-2xl dark:bg-gray-800 w-1/2">
			<div class="flex flex-row items-start gap-4">
				<img
					src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80"
					class="rounded-lg h-25 w-20"
				/>
				<div class="flex flex-col justify-between w-full h-28">
					<div>
						<p class="text-2xl font-medium text-gray-800 dark:text-white">
							{{current_user.username}}
						</p>
					</div>
					<div class="w-full p-2 bg-blue-100 rounded-lg dark:bg-white">
						<div
							class="flex items-center justify-between text-md text-gray-400 dark:text-black"
						>
							<p class="flex flex-col">
								Friends
								<span
									class="font-bold text-black dark:text-indigo-500 text-center"
								>
									{{current_user.get_friends_size()}}
								</span>
							</p>
							<p class="flex flex-col">
								Gyms
								<span
									class="font-bold text-black dark:text-indigo-500 text-center"
								>
									{{current_user.get_favorite_gyms_size()}}
								</span>
							</p>
							<p class="flex flex-col">
								Attempts
								<span
									class="font-bold text-black dark:text-indigo-500 text-center"
								>
									{{current_user_attempts}}
								</span>
							</p>
						</div>
					</div>
				</div>
			</div>
			<div class="flex items-center justify-between gap-4 mt-6">
				<a
					href="{{ url_for('climber.edit_profile') }}"
					class="w-1/3 px-2 py-2 text-base bg-white border rounded-lg text-grey-500 hover:bg-gray-200 text-center"
					><button type="button">Edit Profile</button></a
				>
				<a
					href="{{url_for('climber.friends')}}"
					class="w-1/3 px-2 py-2 text-base text-white bg-indigo-500 border rounded-lg hover:bg-indigo-700 text-center"
				>
					<button type="button">Add friend</button>
				</a>
				<a
					href="{{url_for('gym.search')}}"
					class="w-1/3 px-2 py-2 text-base bg-white border rounded-lg text-grey-500 hover:bg-gray-200 text-center"
					><button type="button">Find Gyms</button></a
				>
			</div>
		</div>
	</div>

	<section class="bg-gray-900">
		<div class="container px-6 py-10 mx-auto">
			<h1 class="text-2xl font-semibold capitalize lg:text-3xl text-white">
				Attempted Routes
			</h1>
			<p class="text-lg text-gray-600 font-semibold hover:underline">
				Find all your attempted routes from all your gyms.
			</p>
			<div class="grid grid-cols-1 gap-8 mt-8 md:mt-16 md:grid-cols-2">
				{% for att in attempts %}
				<div class="lg:flex bg-white rounded-lg">
					<img
						class="object-cover w-full h-56 rounded-lg lg:w-64"
						src="https://images.unsplash.com/photo-1515378960530-7c0da6231fb1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
						alt=""
					/>

					<div class="flex flex-col justify-between py-6 lg:mx-6">
						<a
							href="{{ url_for('route.view', route_id=att.route.id) }}"
							class="text-xl font-semibold hover:underline"
						>
							{{ att.route.name }}
						</a>
						<p class="text-xs font-semibold">Time: {{ att.time.strftime('%Y-%m-%d %H:%M:%S') }}</p>
						<p class="text-xs font-semibold">Grade: {{ att.grade }}</p>
						<span
							class="badge {{ 'badge-success' if att.success else 'badge-danger' }}"
						>
							{{ 'Success' if att.success else 'Failed' }}
						</span>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</section>
</div>
<!-- ====== Footer Section Start -->
<footer class="px-4 py-8 dark:bg-gray-800 dark:text-gray-400">
	<div
		class="container flex flex-wrap items-center justify-center mx-auto space-y-4 sm:justify-between sm:space-y-0"
	>
		<div class="flex flex-row pr-3 space-x-4 sm:space-x-8">
			<a href="/" class="text-indigo-600 text-lg">
				<strong>RouteRater</strong>
			</a>
			<ul class="flex flex-wrap items-center space-x-4 sm:space-x-8">
				<li>
					<a rel="noopener noreferrer" href="#">Terms of Use</a>
				</li>
				<li>
					<a rel="noopener noreferrer" href="#">Privacy</a>
				</li>
			</ul>
		</div>
		<ul class="flex flex-wrap pl-3 space-x-4 sm:space-x-8">
			<li>
				<a rel="noopener noreferrer" href="#">GitHub</a>
			</li>
			<li>
				<a rel="noopener noreferrer" href="#">Instagram</a>
			</li>
			<li>
				<a rel="noopener noreferrer" href="#">Twitter</a>
			</li>
		</ul>
	</div>
</footer>
<!-- ====== Footer Section End -->
{% endblock %}

src/templates/climber/register.html
{% from "_formhelpers.html" import render_field, render_errors%}

{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center mb-4">Sign Up</h1>
      <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ render_field(form.username) }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ render_errors(errors) }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
        </div>
      </form>
      <p class="text-center">
        Already have an account? <a href="{{ url_for('climber.login') }}">Log in</a>.
      </p>
    </div>
  </div>
{% endblock %}