src/rater/models/route.py
from rater import app
from bson.objectid import ObjectId
from datetime import datetime

db = app.config['MONGO']

class Route:
    def __init__(self, name, color, gym_id, _id=None):
        self.id = _id if _id is not None else ObjectId()
        self.name = name
        self.color = color
        self.gym_id = gym_id

    def save(self):
        # Check for unique route name
        existing_route = db.routes.find_one({'name': self.name})
        if existing_route is not None:
            raise ValueError(f'A route with the name {self.name} already exists.')

        return db.routes.insert_one(self.to_document())

    def to_document(self):
        return {
            '_id': self.id,
            'name': self.name,
            'color': self.color,
            'gym': self.gym_id,
        }

    @staticmethod
    def from_document(doc):
        return Route(
            doc['name'],
            doc['color'],
            doc['gym'],
            doc['_id'],
        )

    @staticmethod
    def find_by_id(_id):
        if type(_id) is str:
            _id = ObjectId(_id)
        route_doc = db.routes.find_one({'_id': _id})
        if route_doc is None:
            return None
        return Route.from_document(route_doc)

    @staticmethod
    def find_by_name(name):
        route_doc = db.routes.find_one({'name': name})
        if route_doc is None:
            return None
        return Route.from_document(route_doc)

    @staticmethod
    def find_by_gym_id(gym_id):
        routes_doc = db.routes.find({'gym': ObjectId(gym_id)})
        if routes_doc is None:
            return []
        return [Route.from_document(doc) for doc in routes_doc]

    def get_attempts(self):
        from rater.models import Attempt
        return [Attempt.from_document(doc) for doc in db.attempts.find({'route': self.id})]

    def get_comments(self):
        from rater.models import Comment
        return [Comment.from_document(doc) for doc in db.comments.find({'route': self.id})]

    def get_grade_estimates(self):
        from rater.models import GradeEstimate
        return [GradeEstimate.from_document(doc) for doc in db.grade_estimates.find({'route': self.id})]

    def get_num_attempts(self):
        #return db.attempts.find({'route_id': self.id}).count()
        return db.attempts.count_documents({'route_id': self.id})

    def get_num_comments(self):
        #return db.comments.find({'route': self.id}).count()
        return db.comments.count_documents({'route_id': self.id})

    def get_num_grade_estimates(self):
        #return db.grade_estimates.find({'route': self.id}).count()
        return db.grade_estimates.count_documents({'route_id': self.id})

    def get_grade_estimate(self):
        attempts =  list(db.attempts.find({'route_id': self.id, 'grade': {"$exists": True}}, {"grade":1, "_id":0}))
        attempts = list(map(lambda x: x["grade"], attempts))
        
        total = 0
        for a in attempts:
            total += a
        
        if len(attempts) == 0:
            return None

        avg = total / len(attempts)

        return avg

src/rater/controllers/climber.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, current_user, logout_user, login_required
from rater.forms import RegistrationForm, LoginForm, AttemptForm
from rater.models import Climber, Route, Attempt, Gym


climber_bp = Blueprint('climber', __name__)


@climber_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        # Create new climber
        climber = Climber(email=form.email.data, username=form.username.data)
        climber.set_password(form.password.data)

        # Save climber to database
        try:
            climber.save()
        except ValueError as e:
            errors = [str(e)]
            return render_template('climber/register.html', form=form, current_user=current_user, errors=errors)

        # Log in new user and redirect to index page
        login_user(climber)
        return redirect(url_for('index'))

    # Render sign-up page
    return render_template('climber/register.html', form=form, current_user=current_user)


@climber_bp.route('/login', methods=['GET', 'POST'])
def login():

    # if climber is logged in redirect to index page
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = LoginForm()

    if form.validate_on_submit():
        # Get climber from database
        climber = Climber.find_by_email(form.email.data)

        # Check if climber exists and password is correct
        if climber is None or not climber.check_password(form.password.data):
            errors = ['Invalid email or password']
            return render_template('climber/login.html', form=form, current_user=current_user, errors=errors)

        # Log in user and redirect to index page
        login_user(climber)
        return redirect(url_for('gym.search'))

    # Render login page
    return render_template('climber/login.html', form=form, current_user=current_user)


@climber_bp.route('/logout')
def logout():
    # Log out the current user
    logout_user()

    # Redirect to the login page
    return redirect(url_for('climber.login'))


@climber_bp.route('/profile')
def profile():
    attempts = Attempt.find_by_climber(current_user)
    current_user.get_favorite_gyms = lambda: Gym.get_favorite_gyms(
        current_user)
    current_user.get_favorite_gyms_size = lambda: Gym.get_favorite_gyms_size(
        current_user)
    current_user_attempts = len(attempts)
    return render_template('climber/profile.html', current_user=current_user, attempts=attempts, current_user_attempts=current_user_attempts)


@climber_bp.route('/profile/edit')
@login_required
def edit_profile():
    return render_template('climber/edit_profile.html')


@climber_bp.route('/profile/friends')
def friends():
    name = request.args.get('name', None)

    climbers = []
    if name:
        climbers = Climber.find_many_by_username(name)

    return render_template('climber/friends.html', current_user=current_user, climbers=climbers)


@climber_bp.route('/profile/add_friend/<user_id>', methods=['GET'])
@login_required
def add_friend(user_id):
    # Retrieve the gym
    user = Climber.find_by_id(user_id)
    if not user or current_user.is_friend(user):
        return redirect(url_for('climber.friends'))

    current_user.add_friend(user)

    # Redirect back to the gym's page
    flash(f'Added {user.username} to your favorites.')
    return redirect(url_for('climber.friends', current_user=current_user, climbers=[]))


@climber_bp.route('/profile/remove_friend/<user_id>', methods=['GET'])
@login_required
def remove_friend(user_id):
    user = Climber.find_by_id(user_id)
    if not user or not current_user.is_friend(user):
        return redirect(url_for('climber.friends'))

    current_user.remove_friend(user)

    flash(f'Removed {user.username} to your favorites.')
    return redirect(url_for('climber.friends', current_user=current_user, climbers=[]))


@climber_bp.route('/route/add/<route_id>', methods=["GET", "POST"])
@login_required
def add_attempt(route_id):
    form = AttemptForm()
    route = Route.find_by_id(route_id)

    if form.validate_on_submit():
        try:
            attempt = Attempt(route_id=route.id, climber_id=current_user.id,
                              success=form.success.data, grade=form.grade.data)
            attempt.save()
        except ValueError as e:
            errors = [str(e)]
            return render_template('route.view', route_id=route_id, errors=errors)

        flash(f'Added attempt for {route.name}.')
        return redirect(url_for('route.view', route_id=route_id))

    return render_template('route/add_attempt.html', route=route, form=form)

src/rater/controllers/route.py
import io
import base64
import qrcode

from bson import ObjectId
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from rater.forms import RouteForm
from rater.models import Gym, Route, Attempt

route_bp = Blueprint('route', __name__)


@route_bp.route('/route/create', methods=['GET', 'POST'])
@login_required
def create():
    form = RouteForm()

    if form.validate_on_submit():

        try:
            # convert gym_id to ObjectId
            gym_id = ObjectId(form.gym_id.data)

            # Create new route
            route = Route(form.name.data, form.color.data, gym_id)
            # Save route to database
            route.save()
        except ValueError as e:
            errors = [str(e)]
            return render_template('route/create.html', form=form, current_user=current_user, errors=errors)

        # Redirect to route page
        return redirect(url_for('route.view', route_id=str(route.id)))

    # Render create gym page
    return render_template('route/create.html', form=form, current_user=current_user)


@route_bp.route('/route/<route_id>')
@login_required
def view(route_id):
    route = Route.find_by_id(route_id)
    if route is None:
        return redirect(url_for('main.index'))

    climber_attempts = Attempt.find_by_route(route)
    estimate = route.get_grade_estimate()

    # Generate the QR code
    qrcode_img = qrcode.make(url_for('route.view', route_id=route_id, _external=True))

    # Save it to a BytesIO object
    buf = io.BytesIO()
    qrcode_img.save(buf)

    # Encode the image in base64 and convert it to a format that can be used in HTML
    qr_code_b64 = base64.b64encode(buf.getvalue()).decode()

    gym = Gym.find_by_id(route.gym_id)

    return render_template('route/read.html', route=route, current_user=current_user, climber_attempts=climber_attempts, estimate=estimate, qr_code_b64=qr_code_b64, gym=gym)

src/templates/route/add_attempt.html
{% from "_formhelpers.html" import render_field, render_errors %}

{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-md-8 col-lg-6 mx-auto">
            <div class="card my-4">
                <div class="card-header text-center">
                    <h1>Add Attempt for {{ route.name }}</h1>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {{ form.csrf_token }}

                        <div class="form-group mb-3">
                            {{ render_field(form.success) }}
                        </div>

                        <div class="form-group mb-3">
                            {{ render_field(form.grade) }}
                        </div>

                        {{ render_errors(errors) }}

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary w-100">Add Attempt</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/route/create.html
{% from "_formhelpers.html" import render_field, render_errors %}

{% extends "base.html" %}

{% block title %}Create Route{% endblock %}

{% block content %}
  <h1>Create Route</h1>
  <form method="POST">
    {{ form.csrf_token }}

    {{ render_field(form.name) }}
    {{ render_field(form.color) }}
    {{ render_field(form.gym_id) }}

    {{ render_errors(errors) }}

    <div class="form-group">
      <button type="submit" class="btn btn-primary">Create</button>
    </div>
  </form>
{% endblock %}

src/templates/route/read.html
{% extends 'base.html' %} {% from 'gym/_macros.html' import route_card %} {%
from 'climber/_macros.html' import attempt_card %} {% block content %}
<div class="bg-gray-900 py-6 sm:py-8 lg:py-12">
	<div class="container">
		<div class="card my-4">
			<div
				class="card-header"
				style="background-color: {{ route.color }}; color: white; text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;"
			>
				<h1 class="mb-0">{{ route.name }}</h1>
			</div>
			<div class="card-body">
				<h3 class="card-text">Estimate Grade: {{ estimate }}</h3>
				<a
					href="{{ url_for('gym.show', gym_id=route.gym_id) }}"
					class="btn btn-primary"
					>View Gym</a
				>
			</div>
		</div>

		{% if current_user.is_authenticated %} {% if current_user.id == gym.owner_id
		or current_user.id in gym.admins %}
		<div class="col-md-4">
			<div class="card my-4">
				<div class="card-header">
					<h3>Admin Controls</h3>
				</div>
				<div class="card-body text-center">
					<!-- Display the QR code -->
					<img
						src="data:image/png;base64,{{ qr_code_b64 }}"
						alt="QR Code"
						style="width: 200px; height: 200px"
					/>

					<!-- Provide a download link -->
					<div class="mt-2">
						<a
							href="data:image/png;base64,{{ qr_code_b64 }}"
							download="qrcode.png"
							class="btn btn-primary"
							>Download QR Code</a
						>
					</div>
				</div>
			</div>
		</div>
		{% endif %}
		<section class="bg-gray-900">
			<div class="container px-6 py-10 mx-auto">
				<h1 class="text-2xl font-semibold capitalize lg:text-3xl text-white">
					Attempts
				</h1>
				<p class="text-lg text-gray-600 font-semibold">
					Take a look at all the attempts for this route.
				</p>
				<a
					href="{{ url_for('climber.add_attempt', route_id=route.id) }}"
					class="btn btn-primary mt-4"
					>Add Attempt</a
				>
				<div class="grid grid-cols-1 gap-8 mt-8 md:mt-16 md:grid-cols-2">
					{% for att in climber_attempts %}
					<div class="lg:flex bg-white rounded-lg">
						<img
							class="object-cover w-full h-56 rounded-lg lg:w-64"
							src="https://images.unsplash.com/photo-1515378960530-7c0da6231fb1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
							alt=""
						/>

						<div class="flex flex-col justify-between py-6 lg:mx-6 text-black">
							<a
								href="{{ url_for('route.view', route_id=att.route.id) }}"
								class="text-xl font-semibold hover:underline"
							>
								{{ att.route.name }}
							</a>
							<p class="text-xs font-semibold">{{ att.time }}</p>
							<p class="text-xs font-semibold">{{ att.grade }}</p>
							<span
								class="badge {{ 'badge-success' if att.success else 'badge-danger' }}"
							>
								{{ 'Success' if att.success else 'Failed' }}
							</span>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</section>
		{% endif %}
	</div>
</div>
<!-- ====== Footer Section Start -->
<footer class="px-4 py-8 dark:bg-gray-800 dark:text-gray-400">
	<div
		class="container flex flex-wrap items-center justify-center mx-auto space-y-4 sm:justify-between sm:space-y-0"
	>
		<div class="flex flex-row pr-3 space-x-4 sm:space-x-8">
			<a href="/" class="text-indigo-600 text-lg">
				<strong>RouteRater</strong>
			</a>
			<ul class="flex flex-wrap items-center space-x-4 sm:space-x-8">
				<li>
					<a rel="noopener noreferrer" href="#">Terms of Use</a>
				</li>
				<li>
					<a rel="noopener noreferrer" href="#">Privacy</a>
				</li>
			</ul>
		</div>
		<ul class="flex flex-wrap pl-3 space-x-4 sm:space-x-8">
			<li>
				<a rel="noopener noreferrer" href="#">GitHub</a>
			</li>
			<li>
				<a rel="noopener noreferrer" href="#">Instagram</a>
			</li>
			<li>
				<a rel="noopener noreferrer" href="#">Twitter</a>
			</li>
		</ul>
	</div>
</footer>
<!-- ====== Footer Section End -->
{% endblock %}